config/routes.rb
Rails.application.routes.draw do
  resources :books
  root to: 'homes#top'
  get 'books/new'
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'book/:id' => 'books#show'
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 def new
   @book = Book.new
 end

 def create
   @book = Book.new(book_params)
   @books = Book.all
   if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to "/books/#{@book.id}"
   else
      render :index
   end
 end

 def index
   @book = Book.new
   @books = Book.all
 end

 def show
   @book = Book.find(params[:id])
 end

 def edit
   @book = Book.find(params[:id])
 end

 def update
   @book = Book.find(params[:id])
   if @book.update(book_params)
    flash[:notice] = "Book was successfully updated."
    redirect_to "/books/#{@book.id}"
   else
    render :edit
   end
 end

 def destroy
   book = Book.find(params[:id])
   book.destroy
   redirect_to books_path
 end

private
 def book_params
    params.require(:book).permit(:title, :category, :body)
 end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/blogs/edit.html.erb
<h1>Blogs#edit</h1>
<p>Find me in app/views/blogs/edit.html.erb</p>

app/views/blogs/index.html.erb
<h1>Blogs#index</h1>
<p>Find me in app/views/blogs/index.html.erb</p>

app/views/blogs/new.html.erb
<h1>Blogs#new</h1>
<p>Find me in app/views/blogs/new.html.erb</p>

app/views/blogs/show.html.erb
<h1>Blogs#show</h1>
<p>Find me in app/views/blogs/show.html.erb</p>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
 <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
 <% end %>

<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>
    <% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this book from being saved:
    <% @book.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
 <% end %>

 <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Update Book' %>
 <% end %>
 <%= link_to "Show",book_path %>
  <%= link_to "Back",books_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
 <thead>
  <tr>
  <th>Title</th>
  <th>Body</th>
   <th colspan="3"></th>
  </tr>
   <% @books.each do |book| %>
  <tr>
    <span><th><%= book.title %></th></span>
    <span><th><%= book.body %></th></span>
    <th><%= link_to "show","/books/#{book.id}" %></th>
    <th><%= link_to "Edit",edit_book_path(book.id)  %></th>
    <th><%= link_to "Destroy",book_path(book),method: :delete, data: { confirm: 'Are you sure?' } %></th>
  </tr>
 <% end %>
</thead>
</table>

<h2>New book</h2>
<%= form_for(@book) do |f| %>
 <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <% @book.errors.full_messages.each do |message| %>
  <%= message %>
 <% end %>
<% end %>
<h4>Title</h4>
 <%= f.text_field :title %>
 <h4>Body</h4>
 <%= f.text_field :body %>
 <%= f.submit %>
<% end %>

app/views/books/show.html.erb
   <% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
   <% end %>

  <h4>Title</h4>
   <%= @book.title %>

  <h4>Body</h4>
   <%= @book.body %>
   <%= link_to "Edit", edit_book_path(@book.id) %>
   <%= link_to "Back",books_path %>

app/views/homes/top.html.erb
<h1>ようこそ Bookers へ！</h1>
<p>Bookers では、さまざまな書籍に関するあなたの意見や<br>
印象を共有し交換することができます</p>
<%= link_to "start","/books" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BOOKERS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>